### PR TITLE
revamped addon setttings window

### PR DESCRIPTION
**Pull request by merlight**
Refs #3 

What should I say? The revamp commit is so large that even diff got lost half-way through.

There are a few `if SomeUpdate6Function then` guards that make this version work on live as well. Naturally they can be removed once update 6 is pushed to live servers.

### CODE REVIEW

**Comment by sirinsidiator** [comment]
I'll review and test it once my PTS finished updating, which will be sometime tomorrow thanks to my slow internet.

**Comment by sirinsidiator** [comment]
Just tested it on the pts and I like it.
Unfortunately it already has part of the visual upgrade tied in. That was what I actually wanted to have separated, but from glancing through the code I guess that is not really feasible.
So I'll wait with merging until we finished the styling part too.

I noticed a few things that I will put into #3 and I also have one feature request for the filter box.
Can you add a clear button on the right end, inside the box that appears once you type something?
Also the box seems to be a bit too wide and does not properly align with the addon list. Maybe you can make it a bit smaller?

**Comment by merlight** [comment]
I wanted to explain that in the comment but had a hard time wording it properly. The last commit (introduce search box) is somewhat optional. You can advance your update6 branch (well unless you have some additional local commits) up to the revamp without the search box with:
git merge --ff c43fb08

**Comment by sirinsidiator** [comment]
The OpenToPanel function should also clear the searchbox.

**Comment by merlight** [comment]
I will remove the searchbox from this pull request, okay? Seems that with all the suggested changes, most of it will be replaced anyway.

**Comment by sirinsidiator** [comment]
Yes. I would like it better if one pull request only contains one feature or change.
Search box and style upgrade are clearly two separated things and should have their own pull request respectively.

**Comment by merlight** [comment]
Re-reading OpenToPanel, I think I got it in the wrong order - it should select the list row first, and then open the menu.

Because if you call OpenToPanel without ever opening the menu, SelectNode triggers the menu callback which populates the list and automatically selects the first row if none is selected.

So I changed the order in OpenToPanel, and while testing it, found out that ZO_ScrollList_ScrollDataIntoView doesn't account for top/bottom fade gradients, so it doesn't scroll enough. I'll try to fix that as well.

**Comment by merlight** [comment]
Replaced the scroll-into-view "improvement" I pushed earlier, because it was seriously broken.

**Comment by sirinsidiator** [comment]
What's the status on this? I just checked this branch out, but don't see any style changes.
I also have conflicts when trying to merge it with my latest changes in the new "development" branch.
I'll close this for now. Can you please create a new pull request against development?

**Comment by merlight** [comment]
This was rebased onto `master`, conflicts were possibly caused by 3a2a7194b8feb8b66b3223be1919f108385d177d changing whitespace in code this one removes. I will rebase onto `development` then.

**Pull request closed without merging**
