### PR TITLE
Minimal comment cleanup and UI warning color.

### PR DESCRIPTION
**Pull request by phuein**
Minimally fix comments' readability. Good preparation for updating the comments.

Also, the red color of the RELOAD_UI_WARNING text was killing my eyes, so I added a panel.data option to set it. Defaults to nil -> default color. Includes new panel table comment. And warning text was shortened for readability.

A small README to help direct new visitors to the docs they're likely wanting.

### CODE REVIEW

**Comment by sirinsidiator** [comment]
The changes to the comments seem fine and I could merge them right away if you split them into a separate request.

As for the reload ui warning, instead of adding a property for the color I'd rather keep it consistent across addons and use a different color for all of them. Seeing as the ingame video settings do not color it at all, we could probably just drop the red. In addition we should also use the same text for the tooltip as is used there.

**Comment by phuein** [comment]
Agreed.

I'll close this pull, make a new pull only for "Table comments cleanup", and make another pull to finalize the reload warning message topic - default color and default game text for it. (Jeez I'm glad you agree with removing the red color in any way hah.)

**Comment by sirinsidiator** [comment]
How fast do you believe you can implement the changes to the reload warning? Should I wait before I release r29 or will it take longer?

**Comment by phuein** [comment]
As fast as you approve every gradual pull. :D (Jeez Git is annoying.)

**Pull request closed without merging**
